name: Automated Commit

on:
  push:
    branches: [master] # Ensures the workflow triggers on pushes to master

  schedule:
    - cron: '0 */3 * * *' # Executes every 3 hours (8 times a day)

  workflow_dispatch: # Allows manual triggering from the GitHub UI

permissions:
  contents: write # Grants permissions to write to the repo

jobs:
  update_commit:
    runs-on: ubuntu-latest # Specifies the runner

    steps:
      - name: Setup Debug Information
        run: echo "::debug::Triggered by ref = ${{github.ref}}"

      - name: Checkout Code
        uses: actions/checkout@v3 # Latest version for optimized performance
        with:
          persist-credentials: true # Ensures credentials are available for subsequent steps
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Setup Git Configuration
        run: |
          git config user.email "coinnyari@gmail.com"
          git config user.name "bangpateng"

      - name: Generate Multiple Commits
        run: |
          commit_messages=("Update: â°" "Refresh: ðŸ”„" "Renew: ðŸŒŸ" "Revise: ðŸ“" "Amend: ðŸ› " "Adjust: ðŸ”§" "Change: ðŸ“ˆ" "Modify: ðŸ–Š" "Transform: ðŸŒ€" "Revamp: ðŸŒˆ")
          
          # Akan membuat 63 commit setiap kali workflow berjalan (63 x 8 kali sehari = ~500 commit)
          for i in {1..63}
          do
            current_time=$(date '+%Y-%m-%d %H:%M:%S')
            echo "Updated on $current_time - Commit #$i" > TIMESTAMP.txt
            
            random_index=$((RANDOM % ${#commit_messages[@]}))
            random_msg=${commit_messages[$random_index]}
            
            git add TIMESTAMP.txt
            git commit -m "$random_msg - $current_time - #$i"
            
            # Jeda singkat agar timestamp berbeda
            sleep 1
          done
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
